### PR TITLE
Create staticwebsite.txt

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
@nairvarun I found a tic tac toe AI, but this time not hardcoded in CSS, I haven't tested it yet, but here's the repo.

https://github.com/adeelibr/tic-tac-toe-ai-vanilla-js/tree/master/simple

If it's not what you want, you can close this PR and delete that branch for now.

CODE TEST URL: https://tictactoe-ai-test.netlify.app/

The codepen they listed doesn't seem to work but here's a link to it anyway: codepen.io/adeelibr/full/krabaq/

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@nairvarun Just completed my testing, it works perfectly. My only issue is that the bot ai plays its turn so fast, within even a milisecond.

**Comment by KendallDoesCoding** [comment]
You can also set the x and o to be as follows:

X Symbol: ×
O Symbol: ○

**Comment by KendallDoesCoding** [comment]
@nairvarun I const'd it with the new symbols. But it's still not updated, can't figure out the issue.

**Comment by nairvarun** [comment]
its a good reference. i dont think i'm gonna merge it tho. i wanna try and make it from scratch. thanks for all the help

**Comment by KendallDoesCoding** [comment]
> its a good reference. i dont think i'm gonna merge it tho. i wanna try and make it from scratch. thanks for all the help

k cool.

**Pull request closed without merging**
