### PR TITLE
Static website

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
Hey,

I found this code on codepen, you can see what you can do with it. 

Codepen: https://codepen.io/alvaromontoro/pen/BexWOw
Website of project (I made it here, but you can run it straight on the codepen.io) - https://tictactoeai.kendalldoescoding.gq/

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@nairvarun If you wanna merge it here, please create another branch and then merge it there. I can't create another branch coz you own this repo.

**Comment by KendallDoesCoding** [comment]
You can also link the, bot.py version on the html, via a github url, if you want to!

**Comment by KendallDoesCoding** [comment]
You can also add a lot more, like a level system, linked with firebase so other people can see the highscores too, etc.

**Comment by nairvarun** [comment]
ooo interesting. i'll go over the changes by sunday

**Comment by KendallDoesCoding** [comment]
👍

**Comment by KendallDoesCoding** [comment]
@nairvarun Reminder on this!

**Comment by nairvarun** [comment]
ye i went through it. the html and css is a good starting point for the ui but the game logic is hard coded in css which is not what i'm looking for. ty

**Comment by KendallDoesCoding** [comment]
> ye i went through it. the html and css is a good starting point for the ui but the game logic is hard coded in css which is not what i'm looking for. ty

True!

**Pull request closed without merging**
